title: 考古课题组
email: contact@example.com
description: >-
  这里填写课题组简介，例如研究方向、单位和网站定位。
baseurl: ""
url: "https://yyyt03.github.io"
lang: zh-CN
timezone: Asia/Shanghai
github_username: "yyyt03"

theme: minima
plugins:
  - jekyll-feed

collections:
  members:
    output: true
    permalink: /members/:name/
  news:
    output: true
    permalink: /news/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: members
    values:
      layout: page
  - scope:
      path: ""
      type: news
    values:
      layout: page
  - scope:
      path: ""
      type: projects
    values:
      layout: page

exclude:
  - .jekyll-cache/
  - _site/
  - docs/

